### ISSUE TITLE
Git submodule update --init --force not working to pull submodules

### ISSUE THREAD

**Issue by jpilchisu** [isubit/luggage_isu#14]
Tonight I was working out some of the drush version related install issues I've been having when I ran across a git related one: submodules weren't downloading during the install script's run.  From multiple tests, I believe it's caused by the "git submodule update --init --force" line in luggage.sh.  For the last run I separated the commands into:

git submodule init
git submodule update

in the script, and while I got a lot of extra text, I finally got through an entire install. Using the --recursive flag also fixed the problem when I used it during the repo clone.

I'm running Rhel6.6, Git 1.7.1, Drush 6.2 for reference.

**Comment by clouseau** [comment]
Unfortunately git 1.7 is a little hoary. You need 1.8 or later for proper submodule support I think.

**Comment by jpilchisu** [comment]
My drush is too far ahead and my git too far behind.  Oh the irony.  I'll bump up my git and check it out.

**Comment by jpilchisu** [comment]
I can confirm that "git submodule update --init --force" works with at least 2.3.2.  However, separating it into two lines works with both the rhel6 capped git 1.7.1 and the later versions.  Not sure it's worth a pull request, but I thought I'd mention it.  I'll mark as closed.

**Comment by brettKK** [comment]
Git submodule update --init --force         not working to pull submodules
---
how to solved it , i still meet this problem

**Comment by svyatoslavratov** [comment]
+
